[package]
name = "test_deploy"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
axum-prometheus = "0.8.0"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
